FROM ubuntu:20.04

LABEL author="Haruki Anbai" 

SHELL ["/bin/bash", "-c"]

ENV TZ=Asia/Tokyo\
    DEBIAN_FRONTEND=noninteractive

#optを作業ディレクトリとする
WORKDIR /opt

#必要なパッケージをubuntuにインストール
RUN apt-get update && apt-get install -y\
    git\
    wget\
    build-essential\
    libncurses-dev\
    unzip\
    language-pack-ja-base\
    language-pack-ja\
    locales\
    bash-completion\
    source-extractor\
    && rm -rf /var/lib/apt/lists/*

#localeを日本語設定に変更
RUN locale-gen ja_JP.UTF-8

#言語を日本語に設定
ENV LANG ja_JP.UTF-8

# bash_completionsを有効化
RUN echo -en "\n# bash_completion\n. /usr/share/bash-completion/bash_completion\n" >> ~/.bashrc

#miniconda3をインストール
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    chmod 700 ./Miniconda3-latest-Linux-x86_64.sh && \
    bash ./Miniconda3-latest-Linux-x86_64.sh -b && \
    ~/miniconda3/bin/conda init bash && \
    rm ./Miniconda3-latest-Linux-x86_64.sh

#miniconda3のPATHを通す
ENV PATH $PATH:/root/miniconda3/bin

# coias-back-appとfindOrbのPATHを通す
ENV PATH $PATH:/opt/coias-back-app
ENV PATH $PATH:/opt/coias-back-app/findOrb
ENV PATH $PATH:/opt/coias-back-app/COIASlibs
ENV PATH $PATH:/opt/coias-back-app/src1_preprocess
ENV PATH $PATH:/opt/coias-back-app/src2_startsearch2R
ENV PATH $PATH:/opt/coias-back-app/src3_prempsearchC-before
ENV PATH $PATH:/opt/coias-back-app/src4_prempsearchC-after
ENV PATH $PATH:/opt/coias-back-app/src5_astsearch_new
ENV PATH $PATH:/opt/coias-back-app/src6_between_COIAS_and_ReCOIAS
ENV PATH $PATH:/opt/coias-back-app/src7_AstsearchR_afterReCOIAS
ENV PATH $PATH:/opt/coias-back-app/src8_astsearch_manual
ENV PYTHONPATH $PYTHONPATH:/opt/coias-back-app/COIASlibs